version: '3.8'

services:
  tpecapp:
    build:
      context: .
    platform: linux/amd64
    image: aleksluciano/tpecapp:v1.1
    container_name: tpecapp
    ports:
      - "4004:4004"
    volumes:
      - ./db.sqlite:/app/db.sqlite
    restart: unless-stopped